/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Transactions"
include(":A-Discord-Adventure")
project(":A-Discord-Adventure").projectDir = File("../../A-Discord-Adventure")
